### PR TITLE
default minecraft command teleport fix

### PR DESCRIPTION
**Pull request by alezm00**

### CODE REVIEW

**Comment by rlnt** [comment]
Please provide a source for this change.
I can't see that this permission was changed to teleport instead of tp.
I used the info sheet right here: https://bukkit.gamepedia.com/CraftBukkit_Commands

As long as you can't proof your change, the pull request won't be merged.

**Comment by alezm00** [comment]
> Please provide a source for this change.
> I can't see that this permission was changed to teleport instead of tp.
> I used the info sheet right here: https://bukkit.gamepedia.com/CraftBukkit_Commands
> 
> As long as you can't proof your change, the pull request won't be merged.

https://youtu.be/bm4CO3RQ9WA maybe this will change your mind :)

**Comment by rlnt** [comment]
Thanks for your contribution then. And also for your extra work with the video.

**Review by rlnt — APPROVED** [review]

**Comment by alezm00** [comment]
😁😁

**Comment by EazyFTW** [comment]
Hm... maybe .tp is for an older version of minecraft?

If this is true, you may want to add both and specify the versions in the description of the command.

**Comment by rlnt** [comment]
I thought about that too but didn't have the time yet for testing. If anyone could do that. That would be nice.

**Comment by rlnt** [comment]
Tested by @tedztar 
Seems like the tp permission is used before version 1.15 and the teleport permission since 1.15.

**Comment by rlnt** [comment]
Fixed in
https://github.com/TechsCode/PluginResources/commit/657962f164b8f44c5ecf01716889d88f403a819f

**Pull request merged**
