### PR TITLE
Update UltraPermissions_Spanish.lang

### PR DESCRIPTION
**Pull request by Im-Fran**

### CODE REVIEW

**Comment by DAmNRelentless** [comment]
Next time you create a pull request for permissions:

**Comment by rlnt** [comment]
@SlipperySpelunky could you review this?

**Comment by EazyFTW** [comment]
> @SlipperySpelunky could you review this?

It looks right to me. (I don't know Spanish, but I have 3 years of it in High School, so)

**Comment by Im-Fran** [comment]
You can search some things in google translate, also I'm from Chile and my native language it's Spanish...

**Review by SlipperySpelunky — APPROVED** [review]

**Comment by rlnt** [comment]
Thanks for contributing! :)

**Pull request merged**
