### PR TITLE
Update Database.updb

### PR DESCRIPTION
**Pull request by vermium**
Bungeecord

### CODE REVIEW

**Review by rlnt — COMMENTED** [review]
Needs investigation from Author.

**Comment by rlnt** [comment]
Sorry but bungeecord permissions won't be merged into the permission database.

**Comment by vermium** [comment]
Could you delete this PR?

**Comment by rlnt** [comment]
Pull requests can't be deleted. It's closed and therefor it's done. But you can't delete it fully.

**Pull request closed without merging**
