### PR TITLE
Update for AdvancedChatTorch

### PR DESCRIPTION
**Pull request by Serviettesky**
Hello can you add some permission for plugin AdvancedChatTorch. UltraPerms Have found someone inside the plugin but not the other permission for different group, prefix and suffix.

Spigot link : https://www.spigotmc.org/resources/advancedchattorch-advanced-json-chat-formatting-free.38246/
Github link : https://github.com/MCGamer00000/AdvancedChatTorch

Thank's in advance.

### CODE REVIEW

**Comment by Serviettesky** [comment]
Hello, you have forgot me ???

**Comment by rlnt** [comment]
No, it's just important to check that everything was added correctly and as I am the only one merging these pull requests, it takes some time.
I am currently very busy. I will do this asap but please be a bit more patient.

**Comment by Serviettesky** [comment]
hello, no problem, I didn't mean to hurry. After there is no other way for me to add permissions, directly on my server, can I like group manager or luckyperms?

**Comment by rlnt** [comment]
This is not a support section. Please refer to the Discord for that and do not answer here anymore.
You can manually type in permissions in the game to add them if they are not in the database yet. If you want to know how to do that, please talk to the support on the Discord.

**Comment by EazyFTW** [comment]
To me, this looks like permission players would have to add specifically on their servers. Like, mod, builder, etc.

**Pull request closed without merging**
