### PR TITLE
added AntiXrayHeuristics

### PR DESCRIPTION
**Pull request by silvenlily**
https://www.spigotmc.org/resources/anti-xray-heuristics-1-13-1-14-1-15.72440/
(permissions are half way down the spigot page)

### CODE REVIEW

**Review by rlnt — COMMENTED** [review]
Since it's a premium plugin, I won't be able to check everything.
Therefor make sure the plugin ID is correct. Open the plugin's jar with WinRar (or similar programs) and open the plugin.yml and make sure that the name of the plugin matches the first section for each line. It has to be exactly 'AntiXrayHeuristics'. If it's not, the pull request needs some further changes.

I also removed the wildcard permission since it's not listed in the plugin's permission overview. If the permissions are listed in the plugin.yml and the wildcard permission is included there, just let me know and I will add it back.

**Comment by silvenlily** [comment]
axhPluginJar
axh.* isnt listed, however i gave myself axh.* and can run all of the commands, idk what your rules are for adding a .* permission but it does work.

**Comment by rlnt** [comment]
This could also be the case if you are a server operator. Try to deop yourself and use a command with the wildcard permission and report the result please.

**Comment by silvenlily** [comment]
confirmed I'm not op

**Comment by rlnt** [comment]
Alright, I will add it back then and merge the pull request. Thanks for contributing!

**Review by rlnt — APPROVED** [review]

**Pull request merged**
