### PR TITLE
Update UltraPermissions_French.lang

### PR DESCRIPTION
**Pull request by Azurz**

### CODE REVIEW

**Comment by rlnt** [comment]
@Mitsu13Ion @GoldenLys Could you review these changes if they are correct french?

**Review by Mitsu13Ion — CHANGES_REQUESTED** [review]
@DAmNRelentless Lots of fault :/

**Comment by rlnt** [comment]
> @DAmNRelentless Lots of fault 

Could you suggest changes by reviewing it? Or you can create a pull request on his branch: https://github.com/Azurz/PluginResources/tree/patch-2

**Comment by Mitsu13Ion** [comment]
> 
> 
> > @DAmNRelentless Lots of fault 
> 
> Could you suggest changes by reviewing it? Or you can create a pull request on his branch: https://github.com/Azurz/PluginResources/tree/patch-2

No i cant changes by reviewing it :/

**Comment by Mitsu13Ion** [comment]
@DAmNRelentless I make a PR here ^^

**Comment by rlnt** [comment]
Due to the author not responding, I'll close this pull request.
Reference pull request: #76

**Pull request closed without merging**
