### PR TITLE
Updated the deluxecombat permissions

### PR DESCRIPTION
**Pull request by timderspieler**
Added the new deluxecombat permissions

### CODE REVIEW

**Comment by timderspieler** [comment]
@DAmNRelentless 

Link to the plugin page: https://www.spigotmc.org/resources/63970/
Link to the plugin permissions: https://www.spigotmc.org/wiki/deluxecombat-wiki/

**Comment by timderspieler** [comment]
@DAmNRelentless any news? This is quite important :(

**Review by rlnt — APPROVED** [review]

**Comment by rlnt** [comment]
Thanks for contributing.

**Pull request merged**
