### PR TITLE
Improved dutch by xDizziex

### PR DESCRIPTION
**Pull request by rlnt**

### CODE REVIEW

**Comment by rlnt** [comment]
@iFlyinqMC @RemcoPl Could you review these changes and maybe translate UltraPunishments and InsaneShops?

**Review by RemcoPl — APPROVED** [review]
This is good :)
Approve

**Review by RemcoPl — APPROVED** [review]
This all good
i am dutch 👍

**Comment by rlnt** [comment]
Thanks

**Pull request merged**
