### PR TITLE
Update for AAC

### PR DESCRIPTION
**Pull request by Serviettesky**
Hello, I’m starting to do all the translations of the sentences that explain the different permissions. 
I’ll do this for all the plugins currently in Ultra permission, I hope you can add this to the plugin

### CODE REVIEW

**Comment by rlnt** [comment]
No, permission descriptions stay in English as they won't be translated automatically.
The whole database stays in English.

**Comment by Serviettesky** [comment]
hmmm okay T>T, but i can edit on my plugin or is not work ?

**Comment by rlnt** [comment]
No, the whole permission database is downloaded each restart, you can't make changes to it.
You can ask Tech if he wants to implement more than one database where people can do translations but I doubt this is worth it as we thousands of perms.

**Comment by Serviettesky** [comment]
Okay that's what I was thinking, no probl ^^. I was hot to translate the 6300 lines in French ^^. I'm still going to send a message to Tech to see if he could do something, it will still be very practical for people who don't necessarily master English well.
Thank for your answer ^^

**Pull request closed without merging**
